name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: waka_7e0286a2-a579-41a8-950d-b4c445af3619
          GH_TOKEN: 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
